<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <Authors>FluentDownloader</Authors>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <!--  模块是类库：默认不会把 NuGet 依赖拷进自身 bin，这里强制拷贝，
          使模块输出自包含，主程序复制后即可运行时加载  -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
</Project>
